<?php namespace JuiceLang\Helpers\Classes;

use October\Rain\Parse\MarkdownData;

/**
 * Class Markdown
 * @package JuiceLang\Helpers
 */
class Markdown {
    /**
     * Converts some generated HTML tags
     *
     * @param MarkdownData $data Contains the HTML text generated by the Markdown parser
     * @return void
     */
    static function postMarkdownHook($data) {
        $text = trim($data->text);

        $text = preg_replace('/<em>([^<]*)<\/em>/', '<span class="uk-text-italic">$1</span>', $text);

        $data->text = $text;
    }
}
